apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-lua-functions-check
  namespace: scaffold-test
spec:
  namespace: test-lua-functions
  name: test-lua-functions-check
  repositoryRef:
    kind: GitRepository
    name: scaffold-test
    namespace: scaffold-test
  git:
    ref: main
    folder: /expected/test-lua-functions
  clusterRef:
    name: existing
    namespace: scaffold-test