apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-assert-context-check
  namespace: scaffold-test
spec:
  namespace: test-assert-context
  name: test-assert-context-check
  repositoryRef:
    kind: GitRepository
    name: scaffold-test
    namespace: scaffold-test
  git:
    ref: main
    folder: /expected/test-assert-context
  clusterRef:
    name: existing
    namespace: scaffold-test