apiVersion: v1
kind: ConfigMap
metadata:
  name: reference-values
data:
  reference.yaml: |-
    affinity: {}
    image:
      pullPolicy: IfNotPresent
      repository: nginx
      tag: 1.29.0
    nodeSelector: {}
    replicaCount: 2
    resources: {}
    service:
      port: 80
      type: ClusterIP
    tolerations: []