apiVersion: v1
kind: ConfigMap
metadata:
  name: reference-values
data:
  reference.yaml: |-
    containers:
      - image: nginx:latest
        name: nginx
    namespace: default
    podLabels:
      app: frontend
      env: prod
      tier: backend